import { useState, useEffect } from 'react';
import Layout from '../components/Layout';
import { monthlyReport, monthlyEnergy } from '../data/mockData';
import {
  BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, Cell
} from 'recharts';
import { apiGet } from '../api/api';
import { FileDown, TrendingDown, Leaf, Zap, DollarSign } from 'lucide-react';

export default function Reports() {
  const [r,       setR]       = useState(monthlyReport);
  const [history, setHistory] = useState(monthlyEnergy);

  useEffect(() => {
    apiGet('/reports/monthly').then(data => {
      if (data?.month) setR(data);
    }).catch(() => {});

    apiGet('/energy/analytics').then(data => {
      if (data?.monthly?.length) setHistory(data.monthly);
    }).catch(() => {});
  }, []);

  const budgetPct = Math.round((r.totalCost / r.budgetTotal) * 100);

  const handlePDF = () => { window.print(); };

  return (
    <Layout title="Monthly Report">
      {/* Header actions */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 24 }}>
        <div>
          <h2 style={{ fontFamily: 'Space Grotesk', fontSize: 22, fontWeight: 700 }}>
            Report for {r.month}
          </h2>
          <p style={{ color: 'var(--text-muted)', fontSize: 13, marginTop: 4 }}>
            Auto-generated by EcoSmart Hub AI · Updated daily
          </p>
        </div>
        <button className="btn btn-primary" onClick={handlePDF}>
          <FileDown size={15} /> Download PDF
        </button>
      </div>

      {/* KPI row */}
      <div className="stat-grid section-gap">
        <div className="stat-card green">
          <div className="stat-icon green"><Zap size={20} /></div>
          <div className="stat-value">{r.totalKwh}</div>
          <div className="stat-label">Total kWh consumed</div>
          <div className="stat-delta up">↓ {r.savingPct}% vs last month</div>
        </div>
        <div className="stat-card blue">
          <div className="stat-icon blue"><DollarSign size={20} /></div>
          <div className="stat-value">₸{r.totalCost.toLocaleString()}</div>
          <div className="stat-label">Total electricity cost</div>
          <div className="stat-delta up">↓ ₸{r.saving.toLocaleString()} saved</div>
        </div>
        <div className="stat-card yellow">
          <div className="stat-icon yellow"><TrendingDown size={20} /></div>
          <div className="stat-value">{r.avgDaily}</div>
          <div className="stat-label">Average daily kWh</div>
          <div className="stat-delta neutral">vs 16.8 last month</div>
        </div>
        <div className="stat-card green">
          <div className="stat-icon green"><Leaf size={20} /></div>
          <div className="stat-value">{r.co2Kg} kg</div>
          <div className="stat-label">CO₂ emissions saved</div>
          <div className="stat-delta up">↑ +28 kg vs goal</div>
        </div>
      </div>

      <div className="grid-21 section-gap">
        {/* Chart */}
        <div className="card">
          <div className="card-header">
            <div className="card-title">8-Month Consumption History</div>
          </div>
          <ResponsiveContainer width="100%" height={220}>
            <BarChart data={history} margin={{ top: 5, right: 10, bottom: 0, left: -15 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="rgba(42,47,69,0.8)" vertical={false} />
              <XAxis dataKey="month" tick={{ fill: 'var(--text-muted)', fontSize: 11 }} axisLine={false} tickLine={false} />
              <YAxis tick={{ fill: 'var(--text-muted)', fontSize: 11 }} axisLine={false} tickLine={false} />
              <Tooltip formatter={(v, n) => [`${v} kWh`, 'Consumption']} />
              <Bar dataKey="kwh" radius={[5,5,0,0]}>
                {history.map((e, i) => (
                  <Cell key={i} fill={e.partial ? '#4ade80' : '#60a5fa'} />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>

        {/* Saving summary */}
        <div className="card">
          <div className="card-header">
            <div className="card-title">Saving Breakdown</div>
          </div>

          <div style={{ padding: '6px 0' }}>
            {[
              { label: 'Cost last month',   value: `₸${r.prevCost.toLocaleString()}`,    color: 'var(--danger)' },
              { label: 'Cost this month',   value: `₸${r.totalCost.toLocaleString()}`,   color: 'var(--primary)' },
              { label: 'Total saved',       value: `₸${r.saving.toLocaleString()}`,      color: 'var(--primary)', bold: true },
              { label: 'Saving percentage', value: `${r.savingPct}%`,                    color: 'var(--accent)',  bold: true },
            ].map(item => (
              <div key={item.label} style={{
                display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                padding: '12px 0', borderBottom: '1px solid var(--border)'
              }}>
                <span style={{ fontSize: 13, color: 'var(--text-secondary)' }}>{item.label}</span>
                <span style={{
                  fontSize: item.bold ? 18 : 14,
                  fontWeight: item.bold ? 700 : 600,
                  color: item.color,
                  fontFamily: item.bold ? 'Space Grotesk' : undefined
                }}>{item.value}</span>
              </div>
            ))}
          </div>

          <div style={{ marginTop: 16 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12, color: 'var(--text-muted)', marginBottom: 6 }}>
              <span>Budget utilization</span>
              <span style={{ color: 'var(--primary)' }}>{budgetPct}% used</span>
            </div>
            <div className="progress-bar" style={{ height: 8 }}>
              <div className="progress-fill" style={{
                width: `${budgetPct}%`,
                background: 'linear-gradient(90deg, #4ade80, #22c55e)'
              }} />
            </div>
          </div>
        </div>
      </div>

      {/* Top devices */}
      <div className="grid-12 section-gap">
        <div className="card">
          <div className="card-header">
            <div className="card-title">Top Consuming Devices</div>
          </div>
          <div className="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>#</th>
                  <th>Device</th>
                  <th>kWh</th>
                  <th>Share</th>
                  <th>Cost</th>
                </tr>
              </thead>
              <tbody>
                {r.topDevices.map((d, i) => (
                  <tr key={d.name}>
                    <td>
                      <span style={{
                        width: 22, height: 22, borderRadius: 6,
                        background: i === 0 ? 'var(--warning-dim)' : 'var(--bg-base)',
                        color: i === 0 ? 'var(--warning)' : 'var(--text-muted)',
                        display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
                        fontSize: 12, fontWeight: 700
                      }}>{i + 1}</span>
                    </td>
                    <td style={{ fontWeight: 600, color: 'var(--text-primary)' }}>{d.name}</td>
                    <td>{d.kwh} kWh</td>
                    <td>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                        <div className="progress-bar" style={{ width: 70 }}>
                          <div className="progress-fill"
                            style={{ width: `${d.pct}%`, background: 'var(--accent)' }} />
                        </div>
                        <span>{d.pct}%</span>
                      </div>
                    </td>
                    <td style={{ color: 'var(--danger)', fontWeight: 600 }}>₸{d.cost.toLocaleString()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* AI tips summary */}
        <div className="card">
          <div className="card-header">
            <div className="card-title">AI Recommendations Summary</div>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {r.recommendations.map((rec, i) => (
              <div key={i} style={{
                display: 'flex', gap: 12, padding: '12px 14px',
                background: 'var(--bg-base)', borderRadius: 'var(--radius-sm)',
                border: '1px solid var(--border)'
              }}>
                <span style={{
                  width: 22, height: 22, borderRadius: 6, background: 'var(--primary-dim)',
                  color: 'var(--primary)', display: 'inline-flex',
                  alignItems: 'center', justifyContent: 'center',
                  fontSize: 12, fontWeight: 700, flexShrink: 0, marginTop: 1
                }}>{i + 1}</span>
                <span style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.5 }}>{rec}</span>
              </div>
            ))}
          </div>

          <div style={{
            marginTop: 16, padding: '14px', background: 'var(--primary-dim)',
            borderRadius: 'var(--radius-sm)', border: '1px solid rgba(74,222,128,0.2)',
            textAlign: 'center'
          }}>
            <div style={{ fontSize: 20, fontWeight: 700, color: 'var(--primary)', fontFamily: 'Space Grotesk' }}>
              ₸5 811
            </div>
            <div style={{ fontSize: 12, color: 'var(--text-muted)', marginTop: 3 }}>
              Total potential saving if all tips applied
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
}
